language: python
dist: bionic
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - sudo add-apt-repository ppa:ubuntugis/ppa -y && sudo apt-get update -y
  - sudo apt update
  - sudo apt-get install gdal-bin python-gdal
  - sudo apt-get install libgdal-dev
  - pip install -r requirements.txt
  - git clone https://github.com/smithsg84/pf-mask-utilities.git $HOME/pf-mask-utilities
  - cd $HOME/pf-mask-utilities
  - sed -i 's|-Ithird-party|-Ithird-party -I/usr/include/tcl|' Makefile
  - make
  - cd -
  - chmod +x run_tests.sh
# environment variable
env:
  - PFMASKUTILS=$HOME/pf-mask-utilities CPLUS_INLCUDE_PATH=/usr/include/gdal C_INCLUDE_PATH=/usr/include/gdal
# command to run tests
script:
  - bash ./run_tests.sh